### ISSUE TITLE
Error on 6.1 on ember 3.5 - Expected Broccoli node, got undefined for inputNodes[0]

### ISSUE THREAD

**Issue by carlosgalveias** [Glavin001/ember-jsoneditor#21]
Brocolli throws this when starting 

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
    at BroccoliMergeTrees.Plugin (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\broccoli-plugin\index.js:23:13)
    at new BroccoliMergeTrees (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-jsoneditor\node_modules\broccoli-merge-trees\index.js:16:10)
    at Class.treeForVendor (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-jsoneditor\index.js:33:12)
    at Class._treeFor (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\models\addon.js:616:33)
    at Class.treeFor (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\models\addon.js:576:21)
    at project.addons.reduce (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:700:26)
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:698:32)
    at EmberApp.addonTreesFor (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:722:17)
    at EmberApp.getExternalTree (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:1256:30)
    at EmberApp.toArray (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:1620:12)
    at EmberApp.toTree (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\broccoli\ember-app.js:1750:36)
    at module.exports (C:\Work\IBM\git\bluedarwin-robotic-studio\ember-cli-build.js:27:14)
    at Builder.readBuildFile (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Work\IBM\git\bluedarwin-robotic-studio\node_modules\ember-cli\lib\models\builder.js:32:10)

=================================================================================

This does not happen on 5.x version.

**Comment by maxwondercorn** [comment]
Are you getting the error when using it as an addon, not running the dummy app?

**Comment by maxwondercorn** [comment]
fixed with pr #22
